#!/bin/sh

# $1 is name of example to run

usage='Usage:\n  checkExample xxx \n   e.g.  checkExample blink'

case $# in
    0)echo "${usage}"; exit 1 ;;
    1) ;;
    *) echo "${usage}"; exit 1 ;;
  esac

mkdir -p examplesNewStatus

echo "x" >examplesNewStatus/$1

eval  cargo build  --target ${TARGET}  --features ${HAL},${MCU}  --example  $1  ; RC=$?

echo "y" >examplesNewStatus/$1

exit ${RC} 
