#!/bin/sh

# check status and push if there are updates.
# (previously just pushed all the time, but that often caused conflicts.)

usage='Usage:\n  pushIfNeeded'

case $# in
    0) ;;
    *) echo "${usage}"; exit 1 ;;
  esac

echo ${PWD}

git commit -m "commiting new examplesStatus/${BOARD}."  ; RC=$?
# commit has non-zero return code if there is nothing to commit.

if [ ${RC} -eq  0 ]; then 
   git  pull  ;  git push    # narrow chance of conflict (expected head...) with parallel jobs 
   echo  pushed examplesStatus/${BOARD} on gh-pages branch.
else
   RC=0
   echo  nothing to push.
fi

exit ${RC} 
